# Generated by Django 6.1 on 2026-09-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("case_api", "0002_remove_endpoint_name_caseapiinfo_caseapi_delete_case"),
        ("case_ui", "0002_rename_case_caseui"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="套件名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="套件名称"
                    ),
                ),
                (
                    "case_api_list",
                    models.ManyToManyField(
                        to="case_api.caseapi", verbose_name="接口测试用例id"
                    ),
                ),
                (
                    "case_ui_list",
                    models.ManyToManyField(
                        to="case_ui.caseui", verbose_name="UI测试用例id"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                        verbose_name="项目id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=256, verbose_name="用例路径")),
                (
                    "is_pass",
                    models.BooleanField(default=False, verbose_name="是否通过"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "初始化"),
                            (1, "准备开始"),
                            (2, "正在执行"),
                            (3, "正在输出报告"),
                            (4, "执行完毕"),
                            (-1, "执行出错"),
                        ],
                        verbose_name="用例状态",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suite.suite",
                        verbose_name="测试套件id",
                    ),
                ),
            ],
        ),
    ]
