# Generated by Django 6.1 on 2026-09-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0005_remove_caseapiinfo_api_args"),
        ("case_ui", "0002_rename_case_caseui"),
        ("suite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runresult",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "初始化"),
                    (1, "正在执行"),
                    (2, "正在输出报告"),
                    (3, "执行完毕"),
                    (4, "报告输出完毕"),
                    (-1, "执行出错"),
                ],
                default=0,
                verbose_name="用例状态",
            ),
        ),
        migrations.AlterField(
            model_name="suite",
            name="case_api_list",
            field=models.ManyToManyField(
                blank=True, to="case_api.caseapi", verbose_name="接口测试用例id"
            ),
        ),
        migrations.AlterField(
            model_name="suite",
            name="case_ui_list",
            field=models.ManyToManyField(
                blank=True, to="case_ui.caseui", verbose_name="UI测试用例id"
            ),
        ),
    ]
