# Generated by Django 6.1 on 2026-09-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0002_alter_runresult_status_alter_suite_case_api_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="cron",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="运行表达式"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="run_type",
            field=models.CharField(
                choices=[("O", "Once"), ("C", "Cron")],
                default="O",
                verbose_name="运行模式",
            ),
        ),
    ]
