# Generated by Django 6.1 on 2026-09-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_q", "0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more"),
        ("suite", "0003_suite_cron_suite_run_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_q.schedule",
            ),
        ),
    ]
