# Generated by Django 6.1 on 2026-10-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0004_suite_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="hook",
            field=models.CharField(blank=True, max_length=255, verbose_name="hook密钥"),
        ),
        migrations.AlterField(
            model_name="suite",
            name="run_type",
            field=models.CharField(
                choices=[("O", "Once"), ("C", "Cron"), ("WEBHOOK", "Webhook")],
                default="O",
                verbose_name="运行模式",
            ),
        ),
    ]
