# Generated by Django 6.1 on 2026-09-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Positon",
            new_name="Position",
        ),
    ]
