# Generated by Django 6.1 on 2026-09-18 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="ui测试用例名称"),
                ),
                (
                    "allure",
                    models.JSONField(blank=True, null=True, verbose_name="allure参数"),
                ),
                (
                    "step",
                    models.JSONField(blank=True, null=True, verbose_name="用例步骤"),
                ),
                (
                    "parametrize",
                    models.JSONField(blank=True, null=True, verbose_name="参数化参数"),
                ),
                (
                    "validate",
                    models.JSONField(blank=True, null=True, verbose_name="断言参数"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_ui",
                        to="project.project",
                        verbose_name="项目id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="元素名称")),
                ("locator", models.JSONField(verbose_name="定位")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                        verbose_name="项目id",
                    ),
                ),
            ],
        ),
    ]
