# Generated by Django 6.1 on 2026-09-22 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_ui", "0002_rename_case_caseui"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseui",
            name="element",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="case_ui.element",
                verbose_name="页面元素id",
            ),
        ),
    ]
