# Generated by Django 6.1 on 2026-09-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_ui", "0003_caseui_element"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseui",
            name="allure",
        ),
        migrations.RemoveField(
            model_name="caseui",
            name="element",
        ),
        migrations.RemoveField(
            model_name="caseui",
            name="name",
        ),
        migrations.RemoveField(
            model_name="caseui",
            name="parametrize",
        ),
        migrations.RemoveField(
            model_name="caseui",
            name="step",
        ),
        migrations.RemoveField(
            model_name="caseui",
            name="validate",
        ),
        migrations.CreateModel(
            name="CaseUIInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="ui测试用例名称"),
                ),
                (
                    "allure",
                    models.JSONField(blank=True, null=True, verbose_name="allure参数"),
                ),
                (
                    "step",
                    models.JSONField(blank=True, null=True, verbose_name="用例步骤"),
                ),
                (
                    "parametrize",
                    models.JSONField(blank=True, null=True, verbose_name="参数化参数"),
                ),
                (
                    "validate",
                    models.JSONField(blank=True, null=True, verbose_name="断言参数"),
                ),
                (
                    "element",
                    models.ManyToManyField(
                        to="case_ui.element", verbose_name="页面元素id"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="caseui",
            name="caseuiinfo",
            field=models.ManyToManyField(
                to="case_ui.caseuiinfo", verbose_name="ui测试用例id"
            ),
        ),
    ]
