# Generated by Django 6.1 on 2026-09-18 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="接口名称")),
                ("method", models.CharField(max_length=8, verbose_name="请求方法")),
                ("url", models.CharField(max_length=255, verbose_name="网址")),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        max_length=10240,
                        null=True,
                        verbose_name="查询字符串",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="表单参数"
                    ),
                ),
                (
                    "json",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="JSON参数"
                    ),
                ),
                (
                    "cookies",
                    models.JSONField(
                        blank=True,
                        max_length=10240,
                        null=True,
                        verbose_name="COOKIE信息",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="请求头"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                        verbose_name="项目id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="接口测试用例名称"),
                ),
                (
                    "allure",
                    models.JSONField(blank=True, null=True, verbose_name="allure参数"),
                ),
                (
                    "api_args",
                    models.JSONField(
                        blank=True, null=True, verbose_name="接口用例参数"
                    ),
                ),
                (
                    "extract",
                    models.JSONField(blank=True, null=True, verbose_name="提取参数"),
                ),
                (
                    "parametrize",
                    models.JSONField(blank=True, null=True, verbose_name="参数化参数"),
                ),
                (
                    "validate",
                    models.JSONField(blank=True, null=True, verbose_name="断言参数"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_api",
                        to="project.project",
                        verbose_name="项目id",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="case_api.endpoint",
                        verbose_name="接口id",
                    ),
                ),
            ],
        ),
    ]
