# Generated by Django 6.1 on 2026-09-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="name",
        ),
        migrations.CreateModel(
            name="CaseAPIInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allure",
                    models.JSONField(blank=True, null=True, verbose_name="allure参数"),
                ),
                (
                    "api_args",
                    models.JSONField(
                        blank=True, null=True, verbose_name="接口用例参数"
                    ),
                ),
                (
                    "extract",
                    models.JSONField(blank=True, null=True, verbose_name="提取参数"),
                ),
                (
                    "parametrize",
                    models.JSONField(blank=True, null=True, verbose_name="参数化参数"),
                ),
                (
                    "validate",
                    models.JSONField(blank=True, null=True, verbose_name="断言参数"),
                ),
                (
                    "endpoint",
                    models.ManyToManyField(
                        to="case_api.endpoint", verbose_name="接口id"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="接口测试用例名称"),
                ),
                (
                    "case_path",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=126,
                        null=True,
                        verbose_name="测试用例文件路径",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_api",
                        to="project.project",
                        verbose_name="项目id",
                    ),
                ),
                (
                    "caseapiinfo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="case_api.caseapiinfo",
                        verbose_name="接口信息id",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Case",
        ),
    ]
