# Generated by Django 6.1 on 2026-09-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0002_remove_endpoint_name_caseapiinfo_caseapi_delete_case"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseapi",
            name="caseapiinfo",
            field=models.ManyToManyField(
                blank=True, to="case_api.caseapiinfo", verbose_name="接口信息id"
            ),
        ),
    ]
