# Generated by Django 6.1 on 2026-09-20 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0003_alter_caseapi_caseapiinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseapiinfo",
            name="endpoint",
        ),
        migrations.AddField(
            model_name="caseapiinfo",
            name="endpoint",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="case_api.endpoint",
                verbose_name="接口id",
            ),
            preserve_default=False,
        ),
    ]
