# Generated by Django 6.1 on 2026-09-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0004_remove_caseapiinfo_endpoint_caseapiinfo_endpoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseapiinfo",
            name="api_args",
        ),
    ]
