# Generated by Django 6.1 on 2026-09-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0005_remove_caseapiinfo_api_args"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseapi",
            name="case_path",
        ),
    ]
