# Generated by Django 6.1 on 2026-09-16 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="项目名称")),
                (
                    "description",
                    models.CharField(
                        default="测试项目", max_length=128, verbose_name="项目简介"
                    ),
                ),
                ("base_url", models.CharField(default="", verbose_name="项目网址")),
                (
                    "project_leader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目管理人",
                    ),
                ),
                (
                    "user_list",
                    models.ManyToManyField(
                        blank=True,
                        related_name="project_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目成员",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conftest",
                    models.TextField(default="", verbose_name="pytest项目配置文件"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                        verbose_name="项目",
                    ),
                ),
            ],
        ),
    ]
